CREATE TABLE fb_users(
    id INT(32) NOT NULL,
    firstname VARCHAR(256) NOT NULL,
    lastname VARCHAR(256) NOT NULL,
    img VARCHAR(512) NOT NULL
);

ALTER TABLE fb_users
CHANGE `id` `fb_id` VARCHAR(64) NOT NULL;

ALTER TABLE fb_users
ADD COLUMN `id` INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT FIRST;