CREATE TABLE users(
    id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(250) NOT NULL,
    gender BOOLEAN,
    password VARCHAR(250) NOT NULL,
    img VARCHAR(250) NOT NULL
);

ALTER TABLE users
ADD COLUMN firstname VARCHAR(256) NOT NULL AFTER id,
ADD COLUMN lastname VARCHAR(256) NOT NULL AFTER firstname;

ALTER TABLE users DROP COLUMN gender;